# Generated by Django 3.0.5 on 2020-10-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_upload')),
                ('identified_image', models.ImageField(blank=True, null=True, upload_to='identified_images_upload')),
            ],
        ),
    ]
